version: '3'
services:
  redis:
    image: redis:latest
    container_name: hhplus-redis
    ports:
      - "6379:6379"
    networks:
      - app-net

  mysql:
    image: mysql:8.0
    container_name: hhplus-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: hhplus
      MYSQL_USER: ironjin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - app-net
    volumes:
      - mysql-data:/var/lib/mysql

  mongodb:
    image: mongo:latest
    container_name: hhplus-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ironjin
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: hhplus
    ports:
      - "27017:27017"
    networks:
      - app-net
    volumes:
      - mongo-data:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: hhplus-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: hhplus-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: hhplus-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://hhplus-kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - app-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: hhplus-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: hhplus-kafka:9092
    ports:
      - "8081:8080"
    depends_on:
      - kafka
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  mysql-data:
  mongo-data:
