version: '3'
services:
  redis:
    image: redis:latest
    container_name: hhplus-redis
    ports:
      - "6379:6379"
    networks:
      - app-net

  mysql:
    image: mysql:8.0
    container_name: hhplus-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: hhplus
      MYSQL_USER: ironjin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - app-net
    volumes:
      - mysql-data:/var/lib/mysql

  mongodb:
    image: mongo:latest
    container_name: hhplus-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ironjin
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: hhplus
    ports:
      - "27017:27017"
    networks:
      - app-net
    volumes:
      - mongo-data:/data/db

networks:
  app-net:
    driver: bridge

volumes:
  mysql-data:
  mongo-data:
