global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-boot-app'
    static_configs:
      - targets: ['host.docker.internal:8080']  # Spring Boot 앱 Actuator 엔드포인트
  - job_name: 'docker'
    static_configs:
      - targets: ['prometheus:9090']  # Prometheus 자체 모니터링
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
