spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hhplus?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ironjin
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  cache:
    cache-names: productCache
    redis:
      time-to-live: 86400000 # 1 day in milliseconds

singleServerConfig:
  address: "redis://localhost:6379" # Docker에서 Redis가 실행 중인 호스트
  connectionMinimumIdleSize: 10
  connectionPoolSize: 64