spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  sql:
    init:
      # schema-locations: classpath:sql/database-scheme.sql
      data-locations: classpath:sql/database-data.sql
      encoding: UTF-8
      mode: always

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

jwt:
  secretKey: Ez8RZUiy088e15OapWMfWWMe_kNQglk6GQx3cxAHjhE

management:
  endpoints:
    web:
      exposure:
        include: "*" # 모든 Actuator 엔드포인트 노출
  endpoint:
    metrics:
      enabled: true # /metrics 활성화
  metrics:
    enable:
      all: true # 모든 메트릭 활성화


logging:
  level:
    root: INFO                    # 기본 로그 레벨 (INFO)
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG # 특정 패키지에 대한 로그 레벨 (예: Spring MVC 관련)
    com.hhplus.ecommerce: DEBUG